// MouseSwitch.cs - automatically switches the pointer speed between Mouse and Trackpad
// Detects which device you are using (Raw Input) and adjusts the speed instantly.
// Left-click the tray icon = toggle manually (switches to Manual mode)
// Right-click = menu (Automatic/Manual, Mouse, Trackpad, Settings, Start with Windows,
//               Show last device, Exit)
//
// Build with build.cmd (uses the csc.exe that ships with .NET Framework 4.x). C# 5 only.

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Text;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Web.Script.Serialization;
using System.Windows.Forms;
using Microsoft.Win32;

public static class MouseSpeed {
    [DllImport("user32.dll", EntryPoint="SystemParametersInfo")]
    static extern bool SpiGet(uint action, uint param, ref int value, uint ini);
    [DllImport("user32.dll", EntryPoint="SystemParametersInfo")]
    static extern bool SpiSet(uint action, uint param, IntPtr value, uint ini);
    [DllImport("user32.dll")]
    public static extern bool DestroyIcon(IntPtr handle);

    public static int Get() { int v = 0; SpiGet(0x0070, 0, ref v, 0); return v; }
    // 0x03 = save to the registry and notify the system
    public static void Set(int v) { SpiSet(0x0071, 0, new IntPtr(v), 0x03); }
}

public class RawInputWatcher : NativeWindow {
    [StructLayout(LayoutKind.Sequential)]
    struct RAWINPUTDEVICE { public ushort UsagePage; public ushort Usage; public uint Flags; public IntPtr Target; }
    [StructLayout(LayoutKind.Sequential)]
    struct RAWINPUTHEADER { public uint Type; public uint Size; public IntPtr Device; public IntPtr WParam; }

    [DllImport("user32.dll", SetLastError=true)]
    static extern bool RegisterRawInputDevices(RAWINPUTDEVICE[] devices, uint count, uint size);
    [DllImport("user32.dll")]
    static extern uint GetRawInputData(IntPtr hRawInput, uint command, out RAWINPUTHEADER data, ref uint size, uint headerSize);
    [DllImport("user32.dll", CharSet=CharSet.Unicode, EntryPoint="GetRawInputDeviceInfoW")]
    static extern uint GetRawInputDeviceInfo(IntPtr device, uint command, StringBuilder data, ref uint size);

    const int  WM_INPUT        = 0x00FF;
    const uint RID_HEADER      = 0x10000005;
    const uint RIDI_DEVICENAME = 0x20000007;
    const uint RIDEV_INPUTSINK = 0x00000100;
    const uint RIM_TYPEHID     = 2;

    public event Action<string> DeviceChanged;   // "mouse" or "trackpad"
    public string LastDeviceName = "";
    public string LastKind = "";
    // Only switch away from the current device after it has been idle this long,
    // so using both at the same time does not make the speed flip back and forth
    public int HoldMs = 300;
    string current = "";
    int lastMouse, lastTrackpad;
    Regex mouseRegex;
    Dictionary<IntPtr, string> names = new Dictionary<IntPtr, string>();

    public RawInputWatcher(string mousePattern) {
        mouseRegex = new Regex(mousePattern, RegexOptions.IgnoreCase);
        CreateHandle(new CreateParams());
        uint sz = (uint)Marshal.SizeOf(typeof(RAWINPUTDEVICE));
        RAWINPUTDEVICE[] devs = new RAWINPUTDEVICE[2];
        // Generic mouse (includes pointer movement generated by the touchpad)
        devs[0].UsagePage = 0x01; devs[0].Usage = 0x02; devs[0].Flags = RIDEV_INPUTSINK; devs[0].Target = Handle;
        // Precision touchpad (HID Digitizer / Touch Pad)
        devs[1].UsagePage = 0x0D; devs[1].Usage = 0x05; devs[1].Flags = RIDEV_INPUTSINK; devs[1].Target = Handle;
        if (!RegisterRawInputDevices(devs, 2, sz)) {
            RegisterRawInputDevices(new RAWINPUTDEVICE[] { devs[0] }, 1, sz);
        }
    }

    // Makes the next input fire the event even if the device kind did not change
    public void Reset() { current = ""; }

    string GetName(IntPtr dev) {
        if (dev == IntPtr.Zero) return "";
        string n;
        if (names.TryGetValue(dev, out n)) return n;
        uint size = 0;
        GetRawInputDeviceInfo(dev, RIDI_DEVICENAME, null, ref size);
        StringBuilder sb = new StringBuilder((int)size + 1);
        GetRawInputDeviceInfo(dev, RIDI_DEVICENAME, sb, ref size);
        n = sb.ToString();
        names[dev] = n;
        return n;
    }

    protected override void WndProc(ref Message m) {
        if (m.Msg == WM_INPUT) {
            RAWINPUTHEADER h;
            uint size = (uint)Marshal.SizeOf(typeof(RAWINPUTHEADER));
            if (GetRawInputData(m.LParam, RID_HEADER, out h, ref size, size) != unchecked((uint)-1)) {
                string name = GetName(h.Device);
                string kind;
                if (h.Type == RIM_TYPEHID)          kind = "trackpad"; // touch on the precision touchpad
                else if (h.Device == IntPtr.Zero)   kind = "trackpad"; // movement synthesized by the touchpad
                else if (mouseRegex.IsMatch(name))  kind = "mouse";
                else                                kind = "trackpad";

                LastDeviceName = (name == "") ? "(no identifier - generated by the precision touchpad)" : name;
                LastKind = kind;
                int now = Environment.TickCount;
                if (kind == "mouse") lastMouse = now; else lastTrackpad = now;
                int lastCurrent = (current == "mouse") ? lastMouse : lastTrackpad;
                if (kind != current && (current == "" || unchecked(now - lastCurrent) >= HoldMs)) {
                    current = kind;
                    if (DeviceChanged != null) DeviceChanged(kind);
                }
            }
        }
        base.WndProc(ref m);
    }
}

// ===== Settings (%APPDATA%\MouseSwitch\settings.json) =====
public class Settings {
    public const int    DefaultMouseSpeed    = 12;   // default mouse speed (1-20)
    public const int    DefaultTrackpadSpeed = 20;   // default trackpad speed (1-20)
    // Regex applied to the device name: if it matches, the device is treated as a MOUSE.
    // "VID_" = USB devices (including wireless receivers), "VID&" = Bluetooth.
    public const string DefaultMouseNameMatch = "VID_|VID&";
    // The current device must be idle this long (ms) before switching to the other one.
    public const int    DefaultSwitchHoldMs   = 300;

    public static readonly string Dir  = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "MouseSwitch");
    public static readonly string FilePath = Path.Combine(Dir, "settings.json");

    public int    MouseSpeed     = DefaultMouseSpeed;
    public int    TrackpadSpeed  = DefaultTrackpadSpeed;
    public bool   Auto           = true;
    public string MouseNameMatch = DefaultMouseNameMatch;
    public int    SwitchHoldMs   = DefaultSwitchHoldMs;

    static int LimitSpeed(object value, int def) {
        int n;
        if (value == null || !int.TryParse(Convert.ToString(value, CultureInfo.InvariantCulture), out n)) return def;
        return Math.Min(20, Math.Max(1, n));
    }

    public static Settings Load() {
        Settings s = new Settings();
        try {
            if (!File.Exists(FilePath)) return s;
            Dictionary<string, object> d = new JavaScriptSerializer().DeserializeObject(File.ReadAllText(FilePath)) as Dictionary<string, object>;
            if (d == null) return s;
            object v;
            if (d.TryGetValue("MouseSpeed", out v))    s.MouseSpeed    = LimitSpeed(v, DefaultMouseSpeed);
            if (d.TryGetValue("TrackpadSpeed", out v)) s.TrackpadSpeed = LimitSpeed(v, DefaultTrackpadSpeed);
            if (d.TryGetValue("Auto", out v) && v is bool) s.Auto = (bool)v;
            if (d.TryGetValue("MouseNameMatch", out v) && v is string && IsValidRegex((string)v)) s.MouseNameMatch = (string)v;
            int hold;
            if (d.TryGetValue("SwitchHoldMs", out v) && v != null
                && int.TryParse(Convert.ToString(v, CultureInfo.InvariantCulture), out hold) && hold >= 0) s.SwitchHoldMs = hold;
        } catch { }
        return s;
    }

    static bool IsValidRegex(string pattern) {
        if (pattern == "") return false;
        try { new Regex(pattern); return true; } catch (ArgumentException) { return false; }
    }

    static string JsonString(string s) {
        StringBuilder sb = new StringBuilder("\"");
        foreach (char c in s) {
            if (c == '"' || c == '\\') sb.Append('\\').Append(c);
            else if (c < 0x20) sb.AppendFormat("\\u{0:x4}", (int)c);
            else sb.Append(c);
        }
        return sb.Append('"').ToString();
    }

    public void Save() {
        try {
            Directory.CreateDirectory(Dir);
            string json = "{\r\n"
                + "    \"MouseSpeed\":  " + MouseSpeed + ",\r\n"
                + "    \"TrackpadSpeed\":  " + TrackpadSpeed + ",\r\n"
                + "    \"Auto\":  " + (Auto ? "true" : "false") + ",\r\n"
                + "    \"MouseNameMatch\":  " + JsonString(MouseNameMatch) + ",\r\n"
                + "    \"SwitchHoldMs\":  " + SwitchHoldMs + "\r\n"
                + "}\r\n";
            File.WriteAllText(FilePath, json, new UTF8Encoding(false));
        } catch { }
    }
}

// ===== Start with Windows (per-user Run key, no admin needed) =====
public static class Startup {
    const string RunKey = @"Software\Microsoft\Windows\CurrentVersion\Run";
    const string ValueName = "MouseSwitch";

    static string Command { get { return "\"" + Application.ExecutablePath + "\""; } }

    static string Read() {
        using (RegistryKey k = Registry.CurrentUser.OpenSubKey(RunKey)) {
            return (k == null) ? null : k.GetValue(ValueName) as string;
        }
    }

    public static bool IsEnabled() { return Read() == Command; }

    public static void Set(bool on) {
        using (RegistryKey k = Registry.CurrentUser.CreateSubKey(RunKey)) {
            if (on) k.SetValue(ValueName, Command, RegistryValueKind.String);
            else k.DeleteValue(ValueName, false);
        }
    }

    // Older versions started MouseSwitch.vbs; keep users who had startup enabled enrolled
    public static void MigrateFromScript() {
        try {
            string v = Read();
            if (v != null && v.IndexOf("MouseSwitch.vbs", StringComparison.OrdinalIgnoreCase) >= 0) Set(true);
        } catch { }
    }
}

// ===== Tray and menu =====
public class TrayApp : ApplicationContext {
    static readonly Color Blue  = Color.FromArgb(0, 120, 212);
    static readonly Color Green = Color.FromArgb(16, 137, 62);

    Settings settings;
    string currentMode = "";
    Dictionary<string, Icon> icons = new Dictionary<string, Icon>();
    NotifyIcon tray;
    ToolStripMenuItem itemAuto, itemManual, itemMouse, itemTrackpad, itemStartup;
    RawInputWatcher watcher;

    public TrayApp() {
        settings = Settings.Load();
        Startup.MigrateFromScript();

        tray = new NotifyIcon();
        ContextMenuStrip menu = new ContextMenuStrip();
        itemAuto     = Add(menu, "Mode: Automatic", delegate { SetAuto(true); });
        itemManual   = Add(menu, "Mode: Manual", delegate { SetAuto(false); });
        menu.Items.Add(new ToolStripSeparator());
        itemMouse    = Add(menu, "Mouse", delegate { SetAuto(false); SetMode("mouse", false); });
        itemTrackpad = Add(menu, "Trackpad", delegate { SetAuto(false); SetMode("trackpad", false); });
        menu.Items.Add(new ToolStripSeparator());
        Add(menu, "Settings...", delegate { ShowSettingsDialog(); });
        itemStartup  = Add(menu, "Start with Windows", delegate { Startup.Set(!Startup.IsEnabled()); });
        Add(menu, "Show last device", delegate { ShowLastDevice(); });
        menu.Items.Add(new ToolStripSeparator());
        Add(menu, "Exit (stop MouseSwitch)", delegate { Exit(); });
        tray.ContextMenuStrip = menu;
        menu.Opening += delegate { itemStartup.Checked = Startup.IsEnabled(); };

        // Initial state from the current system speed
        currentMode = (MouseSpeed.Get() == settings.TrackpadSpeed) ? "trackpad" : "mouse";
        BuildIcons();

        watcher = new RawInputWatcher(settings.MouseNameMatch);
        watcher.HoldMs = settings.SwitchHoldMs;
        watcher.DeviceChanged += delegate(string kind) { if (settings.Auto) SetMode(kind, false); };

        tray.MouseClick += delegate(object s, MouseEventArgs e) {
            if (e.Button == MouseButtons.Left) {
                SetAuto(false);
                SetMode(currentMode == "mouse" ? "trackpad" : "mouse", false);
            }
        };

        UpdateUi();
        tray.Visible = true;
    }

    static ToolStripMenuItem Add(ContextMenuStrip menu, string text, EventHandler onClick) {
        ToolStripMenuItem item = new ToolStripMenuItem(text);
        item.Click += onClick;
        menu.Items.Add(item);
        return item;
    }

    // ===== Icons: circle = automatic, square = manual =====
    static Icon NewTrayIcon(string text, Color color, bool round) {
        using (Bitmap bmp = new Bitmap(32, 32)) {
            using (Graphics g = Graphics.FromImage(bmp))
            using (SolidBrush brush = new SolidBrush(color))
            using (Font font = new Font("Segoe UI", 14, FontStyle.Bold, GraphicsUnit.Pixel))
            using (StringFormat fmt = new StringFormat()) {
                g.SmoothingMode = SmoothingMode.AntiAlias;
                g.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
                g.Clear(Color.Transparent);
                if (round) g.FillEllipse(brush, 0, 0, 31, 31); else g.FillRectangle(brush, 1, 1, 30, 30);
                fmt.Alignment = StringAlignment.Center; fmt.LineAlignment = StringAlignment.Center;
                g.DrawString(text, font, Brushes.White, new RectangleF(0, 1, 32, 32), fmt);
            }
            IntPtr hIcon = bmp.GetHicon();
            Icon icon = (Icon)Icon.FromHandle(hIcon).Clone();
            MouseSpeed.DestroyIcon(hIcon);
            return icon;
        }
    }

    void BuildIcons() {
        Dictionary<string, Icon> old = icons;
        icons = new Dictionary<string, Icon>();
        icons["mouse-auto"]      = NewTrayIcon(settings.MouseSpeed.ToString(),    Blue,  true);
        icons["trackpad-auto"]   = NewTrayIcon(settings.TrackpadSpeed.ToString(), Green, true);
        icons["mouse-manual"]    = NewTrayIcon(settings.MouseSpeed.ToString(),    Blue,  false);
        icons["trackpad-manual"] = NewTrayIcon(settings.TrackpadSpeed.ToString(), Green, false);
        // Swap the tray icon before disposing the old ones
        if (currentMode != "") UpdateUi();
        foreach (Icon i in old.Values) i.Dispose();
    }

    void UpdateUi() {
        string suffix = settings.Auto ? "auto" : "manual";
        tray.Icon = icons[currentMode + "-" + suffix];
        string label = (currentMode == "trackpad") ? "Trackpad - " + settings.TrackpadSpeed : "Mouse - " + settings.MouseSpeed;
        tray.Text = settings.Auto ? label + " (automatic)" : label + " (manual)";
        itemAuto.Checked     = settings.Auto;
        itemManual.Checked   = !settings.Auto;
        itemMouse.Text       = "Mouse (" + settings.MouseSpeed + ")";
        itemTrackpad.Text    = "Trackpad (" + settings.TrackpadSpeed + ")";
        itemMouse.Checked    = (currentMode == "mouse");
        itemTrackpad.Checked = (currentMode == "trackpad");
    }

    void SetMode(string mode, bool force) {
        if (force || mode != currentMode) {
            MouseSpeed.Set(mode == "trackpad" ? settings.TrackpadSpeed : settings.MouseSpeed);
            currentMode = mode;
        }
        UpdateUi();
    }

    void SetAuto(bool on) {
        bool changed = (settings.Auto != on);
        settings.Auto = on;
        if (changed) settings.Save();
        if (on) {
            watcher.Reset();
            if (watcher.LastKind != "") SetMode(watcher.LastKind, false); else UpdateUi();
        } else UpdateUi();
    }

    void ShowSettingsDialog() {
        using (Form form = new Form()) {
            form.Text = "MouseSwitch Settings";
            form.FormBorderStyle = FormBorderStyle.FixedDialog;
            form.StartPosition = FormStartPosition.CenterScreen;
            form.MaximizeBox = false; form.MinimizeBox = false;
            form.TopMost = true;
            form.ClientSize = new Size(300, 190);
            form.Font = new Font("Segoe UI", 9);

            Label lblMouse = new Label();
            lblMouse.Text = "Mouse speed (1-20):"; lblMouse.SetBounds(15, 18, 160, 20);
            NumericUpDown numMouse = new NumericUpDown();
            numMouse.Minimum = 1; numMouse.Maximum = 20; numMouse.Value = settings.MouseSpeed;
            numMouse.SetBounds(200, 15, 80, 23);

            Label lblPad = new Label();
            lblPad.Text = "Trackpad speed (1-20):"; lblPad.SetBounds(15, 50, 160, 20);
            NumericUpDown numPad = new NumericUpDown();
            numPad.Minimum = 1; numPad.Maximum = 20; numPad.Value = settings.TrackpadSpeed;
            numPad.SetBounds(200, 47, 80, 23);

            CheckBox chkAuto = new CheckBox();
            chkAuto.Text = "Automatic switching"; chkAuto.Checked = settings.Auto;
            chkAuto.SetBounds(15, 82, 270, 22);

            CheckBox chkStartup = new CheckBox();
            chkStartup.Text = "Start with Windows"; chkStartup.Checked = Startup.IsEnabled();
            chkStartup.SetBounds(15, 108, 270, 22);

            Button btnDefaults = new Button();
            btnDefaults.Text = "Restore defaults"; btnDefaults.SetBounds(15, 148, 110, 28);
            btnDefaults.Click += delegate {
                numMouse.Value = Settings.DefaultMouseSpeed;
                numPad.Value = Settings.DefaultTrackpadSpeed;
                chkAuto.Checked = true;
            };

            Button btnSave = new Button();
            btnSave.Text = "Save"; btnSave.SetBounds(135, 148, 70, 28);
            btnSave.DialogResult = DialogResult.OK;
            Button btnCancel = new Button();
            btnCancel.Text = "Cancel"; btnCancel.SetBounds(210, 148, 70, 28);
            btnCancel.DialogResult = DialogResult.Cancel;
            form.AcceptButton = btnSave;
            form.CancelButton = btnCancel;

            form.Controls.AddRange(new Control[] { lblMouse, numMouse, lblPad, numPad, chkAuto, chkStartup, btnDefaults, btnSave, btnCancel });

            if (form.ShowDialog() == DialogResult.OK) {
                settings.MouseSpeed    = (int)numMouse.Value;
                settings.TrackpadSpeed = (int)numPad.Value;
                settings.Auto          = chkAuto.Checked;
                settings.Save();
                BuildIcons();
                Startup.Set(chkStartup.Checked);
                SetMode(currentMode, true);
                SetAuto(chkAuto.Checked);
            }
        }
    }

    void ShowLastDevice() {
        string kind = (watcher.LastKind == "mouse") ? "MOUSE" : "TRACKPAD";
        MessageBox.Show(
            "Last device used (the one that clicked this menu):\n\n" + watcher.LastDeviceName + "\n\nClassified as: " + kind,
            "MouseSwitch");
    }

    void Exit() {
        tray.Visible = false;
        tray.Dispose();
        foreach (Icon i in icons.Values) i.Dispose();
        watcher.DestroyHandle();
        ExitThread();
    }
}

public static class Program {
    [STAThread]
    public static void Main() {
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);
        Application.SetUnhandledExceptionMode(UnhandledExceptionMode.CatchException);
        Application.ThreadException += delegate(object s, ThreadExceptionEventArgs e) { ShowError(e.Exception); };
        AppDomain.CurrentDomain.UnhandledException += delegate(object s, UnhandledExceptionEventArgs e) { ShowError(e.ExceptionObject as Exception); };

        // Prevent two instances from running
        bool created;
        using (Mutex mutex = new Mutex(true, @"Global\MouseSwitchTray", out created)) {
            if (!created) {
                MessageBox.Show("MouseSwitch is already running. Exit the existing tray icon first.", "MouseSwitch");
                return;
            }
            Application.Run(new TrayApp());
            mutex.ReleaseMutex();
        }
    }

    static void ShowError(Exception ex) {
        MessageBox.Show("Unexpected error:\n\n" + (ex == null ? "(unknown)" : ex.ToString()), "MouseSwitch",
            MessageBoxButtons.OK, MessageBoxIcon.Error);
    }
}
