# MouseSwitch.ps1 - automatically switches the pointer speed between Mouse and Trackpad
# Detects which device you are using (Raw Input) and adjusts the speed instantly.
# Left-click the tray icon = toggle manually (switches to Manual mode)
# Right-click = menu (Automatic/Manual, Mouse, Trackpad, Settings, Start with Windows,
#               Show last device, Exit)

# ===== Configuration =====
$DefaultMouseSpeed    = 12   # default mouse speed (1-20)
$DefaultTrackpadSpeed = 20   # default trackpad speed (1-20)
# Regex applied to the device name: if it matches, the device is treated as a MOUSE.
# "VID_" = USB devices (including wireless receivers), "VID&" = Bluetooth.
# Use "Show last device" in the menu to see the name and adjust if needed.
$MouseNameMatch = 'VID_|VID&'
# The current device must be idle this long (ms) before switching to the other one.
# Prevents flip-flopping when the mouse and the trackpad are used at the same time.
$SwitchHoldMs = 300
# =========================

$SettingsDir  = Join-Path $env:APPDATA 'MouseSwitch'
$SettingsFile = Join-Path $SettingsDir 'settings.json'
$RunKey       = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
$RunValueName = 'MouseSwitch'
$StartupCmd   = "wscript.exe `"$(Join-Path $PSScriptRoot 'MouseSwitch.vbs')`""

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

Add-Type -ReferencedAssemblies System.Windows.Forms -TypeDefinition @"
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Windows.Forms;

public static class MouseSpeed {
    [DllImport("user32.dll", EntryPoint="SystemParametersInfo")]
    static extern bool SpiGet(uint action, uint param, ref int value, uint ini);
    [DllImport("user32.dll", EntryPoint="SystemParametersInfo")]
    static extern bool SpiSet(uint action, uint param, IntPtr value, uint ini);
    [DllImport("user32.dll")]
    public static extern bool DestroyIcon(IntPtr handle);

    public static int Get() { int v = 0; SpiGet(0x0070, 0, ref v, 0); return v; }
    // 0x03 = save to the registry and notify the system
    public static void Set(int v) { SpiSet(0x0071, 0, new IntPtr(v), 0x03); }
}

public class RawInputWatcher : NativeWindow {
    [StructLayout(LayoutKind.Sequential)]
    struct RAWINPUTDEVICE { public ushort UsagePage; public ushort Usage; public uint Flags; public IntPtr Target; }
    [StructLayout(LayoutKind.Sequential)]
    struct RAWINPUTHEADER { public uint Type; public uint Size; public IntPtr Device; public IntPtr WParam; }

    [DllImport("user32.dll", SetLastError=true)]
    static extern bool RegisterRawInputDevices(RAWINPUTDEVICE[] devices, uint count, uint size);
    [DllImport("user32.dll")]
    static extern uint GetRawInputData(IntPtr hRawInput, uint command, out RAWINPUTHEADER data, ref uint size, uint headerSize);
    [DllImport("user32.dll", CharSet=CharSet.Unicode, EntryPoint="GetRawInputDeviceInfoW")]
    static extern uint GetRawInputDeviceInfo(IntPtr device, uint command, StringBuilder data, ref uint size);

    const int  WM_INPUT        = 0x00FF;
    const uint RID_HEADER      = 0x10000005;
    const uint RIDI_DEVICENAME = 0x20000007;
    const uint RIDEV_INPUTSINK = 0x00000100;
    const uint RIM_TYPEHID     = 2;

    public event Action<string> DeviceChanged;   // "mouse" or "trackpad"
    public string LastDeviceName = "";
    public string LastKind = "";
    // Only switch away from the current device after it has been idle this long,
    // so using both at the same time does not make the speed flip back and forth
    public int HoldMs = 300;
    string current = "";
    int lastMouse, lastTrackpad;
    Regex mouseRegex;
    Dictionary<IntPtr, string> names = new Dictionary<IntPtr, string>();

    public RawInputWatcher(string mousePattern) {
        mouseRegex = new Regex(mousePattern, RegexOptions.IgnoreCase);
        CreateHandle(new CreateParams());
        uint sz = (uint)Marshal.SizeOf(typeof(RAWINPUTDEVICE));
        RAWINPUTDEVICE[] devs = new RAWINPUTDEVICE[2];
        // Generic mouse (includes pointer movement generated by the touchpad)
        devs[0].UsagePage = 0x01; devs[0].Usage = 0x02; devs[0].Flags = RIDEV_INPUTSINK; devs[0].Target = Handle;
        // Precision touchpad (HID Digitizer / Touch Pad)
        devs[1].UsagePage = 0x0D; devs[1].Usage = 0x05; devs[1].Flags = RIDEV_INPUTSINK; devs[1].Target = Handle;
        if (!RegisterRawInputDevices(devs, 2, sz)) {
            RegisterRawInputDevices(new RAWINPUTDEVICE[] { devs[0] }, 1, sz);
        }
    }

    // Makes the next input fire the event even if the device kind did not change
    public void Reset() { current = ""; }

    string GetName(IntPtr dev) {
        if (dev == IntPtr.Zero) return "";
        string n;
        if (names.TryGetValue(dev, out n)) return n;
        uint size = 0;
        GetRawInputDeviceInfo(dev, RIDI_DEVICENAME, null, ref size);
        StringBuilder sb = new StringBuilder((int)size + 1);
        GetRawInputDeviceInfo(dev, RIDI_DEVICENAME, sb, ref size);
        n = sb.ToString();
        names[dev] = n;
        return n;
    }

    protected override void WndProc(ref Message m) {
        if (m.Msg == WM_INPUT) {
            RAWINPUTHEADER h;
            uint size = (uint)Marshal.SizeOf(typeof(RAWINPUTHEADER));
            if (GetRawInputData(m.LParam, RID_HEADER, out h, ref size, size) != unchecked((uint)-1)) {
                string name = GetName(h.Device);
                string kind;
                if (h.Type == RIM_TYPEHID)          kind = "trackpad"; // touch on the precision touchpad
                else if (h.Device == IntPtr.Zero)   kind = "trackpad"; // movement synthesized by the touchpad
                else if (mouseRegex.IsMatch(name))  kind = "mouse";
                else                                kind = "trackpad";

                LastDeviceName = (name == "") ? "(no identifier - generated by the precision touchpad)" : name;
                LastKind = kind;
                int now = Environment.TickCount;
                if (kind == "mouse") lastMouse = now; else lastTrackpad = now;
                int lastCurrent = (current == "mouse") ? lastMouse : lastTrackpad;
                if (kind != current && (current == "" || unchecked(now - lastCurrent) >= HoldMs)) {
                    current = kind;
                    if (DeviceChanged != null) DeviceChanged(kind);
                }
            }
        }
        base.WndProc(ref m);
    }
}
"@

# Prevent two instances from running
$created = $false
$mutex = New-Object System.Threading.Mutex($true, "Global\MouseSwitchTray", [ref]$created)
if (-not $created) {
    [System.Windows.Forms.MessageBox]::Show("MouseSwitch is already running. Exit the existing tray icon first.", "MouseSwitch") | Out-Null
    exit
}

# ===== Settings =====
function Limit-Speed($value, [int]$default) {
    $n = 0
    if (-not [int]::TryParse("$value", [ref]$n)) { return $default }
    return [Math]::Min(20, [Math]::Max(1, $n))
}

function Load-Settings {
    $script:MouseSpeed    = $DefaultMouseSpeed
    $script:TrackpadSpeed = $DefaultTrackpadSpeed
    $script:auto          = $true
    if (Test-Path $SettingsFile) {
        try {
            $s = Get-Content $SettingsFile -Raw | ConvertFrom-Json
            $script:MouseSpeed    = Limit-Speed $s.MouseSpeed    $DefaultMouseSpeed
            $script:TrackpadSpeed = Limit-Speed $s.TrackpadSpeed $DefaultTrackpadSpeed
            if ($null -ne $s.Auto) { $script:auto = [bool]$s.Auto }
        } catch { }
    }
}

function Save-Settings {
    try {
        if (-not (Test-Path $SettingsDir)) { New-Item -ItemType Directory -Path $SettingsDir -Force | Out-Null }
        [pscustomobject]@{
            MouseSpeed    = $script:MouseSpeed
            TrackpadSpeed = $script:TrackpadSpeed
            Auto          = $script:auto
        } | ConvertTo-Json | Set-Content -Path $SettingsFile -Encoding UTF8
    } catch { }
}

# ===== Start with Windows (per-user Run key, no admin needed) =====
function Get-Startup {
    $v = (Get-ItemProperty -Path $RunKey -Name $RunValueName -ErrorAction SilentlyContinue).$RunValueName
    return ($v -eq $StartupCmd)
}

function Set-Startup([bool]$on) {
    if ($on) {
        New-ItemProperty -Path $RunKey -Name $RunValueName -Value $StartupCmd -PropertyType String -Force | Out-Null
    } else {
        Remove-ItemProperty -Path $RunKey -Name $RunValueName -ErrorAction SilentlyContinue
    }
}

# ===== Icons: circle = automatic, square = manual =====
function New-TrayIcon([string]$text, [System.Drawing.Color]$color, [bool]$round) {
    $bmp = New-Object System.Drawing.Bitmap 32, 32
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = 'AntiAlias'
    $g.TextRenderingHint = 'AntiAliasGridFit'
    $g.Clear([System.Drawing.Color]::Transparent)
    $brush = New-Object System.Drawing.SolidBrush $color
    if ($round) { $g.FillEllipse($brush, 0, 0, 31, 31) } else { $g.FillRectangle($brush, 1, 1, 30, 30) }
    $font = New-Object System.Drawing.Font("Segoe UI", 14, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
    $fmt = New-Object System.Drawing.StringFormat
    $fmt.Alignment = 'Center'; $fmt.LineAlignment = 'Center'
    $g.DrawString($text, $font, [System.Drawing.Brushes]::White, (New-Object System.Drawing.RectangleF 0, 1, 32, 32), $fmt)
    $g.Dispose()
    $hIcon = $bmp.GetHicon()
    $icon = [System.Drawing.Icon]::FromHandle($hIcon).Clone()
    [MouseSpeed]::DestroyIcon($hIcon) | Out-Null
    $bmp.Dispose()
    return $icon
}

$blue  = [System.Drawing.Color]::FromArgb(0, 120, 212)
$green = [System.Drawing.Color]::FromArgb(16, 137, 62)
$script:icons = @{}

function Build-Icons {
    $old = $script:icons
    $script:icons = @{
        'mouse-auto'      = New-TrayIcon "$($script:MouseSpeed)"    $blue  $true
        'trackpad-auto'   = New-TrayIcon "$($script:TrackpadSpeed)" $green $true
        'mouse-manual'    = New-TrayIcon "$($script:MouseSpeed)"    $blue  $false
        'trackpad-manual' = New-TrayIcon "$($script:TrackpadSpeed)" $green $false
    }
    # Swap the tray icon before disposing the old ones
    if ($tray -and $script:currentMode) { Update-Ui }
    foreach ($i in $old.Values) { $i.Dispose() }
}

# ===== Tray and menu =====
Load-Settings
$script:currentMode = ''

$tray = New-Object System.Windows.Forms.NotifyIcon
$menu = New-Object System.Windows.Forms.ContextMenuStrip
$itemAuto     = $menu.Items.Add("Mode: Automatic")
$itemManual   = $menu.Items.Add("Mode: Manual")
[void]$menu.Items.Add("-")
$itemMouse    = $menu.Items.Add("Mouse")
$itemTrackpad = $menu.Items.Add("Trackpad")
[void]$menu.Items.Add("-")
$itemSettings = $menu.Items.Add("Settings...")
$itemStartup  = $menu.Items.Add("Start with Windows")
$itemInfo     = $menu.Items.Add("Show last device")
[void]$menu.Items.Add("-")
$itemExit     = $menu.Items.Add("Exit (stop MouseSwitch)")
$tray.ContextMenuStrip = $menu
$menu.add_Opening({ $itemStartup.Checked = Get-Startup })

function Update-Ui {
    $suffix = if ($script:auto) { 'auto' } else { 'manual' }
    $tray.Icon = $script:icons["$($script:currentMode)-$suffix"]
    $label = if ($script:currentMode -eq 'trackpad') { "Trackpad - $($script:TrackpadSpeed)" } else { "Mouse - $($script:MouseSpeed)" }
    $tray.Text = if ($script:auto) { "$label (automatic)" } else { "$label (manual)" }
    $itemAuto.Checked     = $script:auto
    $itemManual.Checked   = -not $script:auto
    $itemMouse.Text       = "Mouse ($($script:MouseSpeed))"
    $itemTrackpad.Text    = "Trackpad ($($script:TrackpadSpeed))"
    $itemMouse.Checked    = ($script:currentMode -eq 'mouse')
    $itemTrackpad.Checked = ($script:currentMode -eq 'trackpad')
}

function Set-Mode([string]$mode, [switch]$Force) {
    if ($Force -or $mode -ne $script:currentMode) {
        if ($mode -eq 'trackpad') { [MouseSpeed]::Set($script:TrackpadSpeed) } else { [MouseSpeed]::Set($script:MouseSpeed) }
        $script:currentMode = $mode
    }
    Update-Ui
}

function Set-Auto([bool]$on) {
    $changed = ($script:auto -ne $on)
    $script:auto = $on
    if ($changed) { Save-Settings }
    if ($on) {
        $watcher.Reset()
        if ($watcher.LastKind) { Set-Mode $watcher.LastKind } else { Update-Ui }
    } else { Update-Ui }
}

function Show-SettingsDialog {
    $form = New-Object System.Windows.Forms.Form
    $form.Text = "MouseSwitch Settings"
    $form.FormBorderStyle = 'FixedDialog'
    $form.StartPosition = 'CenterScreen'
    $form.MaximizeBox = $false; $form.MinimizeBox = $false
    $form.TopMost = $true
    $form.ClientSize = New-Object System.Drawing.Size 300, 190
    $form.Font = New-Object System.Drawing.Font("Segoe UI", 9)

    $lblMouse = New-Object System.Windows.Forms.Label
    $lblMouse.Text = "Mouse speed (1-20):"; $lblMouse.SetBounds(15, 18, 160, 20)
    $numMouse = New-Object System.Windows.Forms.NumericUpDown
    $numMouse.Minimum = 1; $numMouse.Maximum = 20; $numMouse.Value = $script:MouseSpeed
    $numMouse.SetBounds(200, 15, 80, 23)

    $lblPad = New-Object System.Windows.Forms.Label
    $lblPad.Text = "Trackpad speed (1-20):"; $lblPad.SetBounds(15, 50, 160, 20)
    $numPad = New-Object System.Windows.Forms.NumericUpDown
    $numPad.Minimum = 1; $numPad.Maximum = 20; $numPad.Value = $script:TrackpadSpeed
    $numPad.SetBounds(200, 47, 80, 23)

    $chkAuto = New-Object System.Windows.Forms.CheckBox
    $chkAuto.Text = "Automatic switching"; $chkAuto.Checked = $script:auto
    $chkAuto.SetBounds(15, 82, 270, 22)

    $chkStartup = New-Object System.Windows.Forms.CheckBox
    $chkStartup.Text = "Start with Windows"; $chkStartup.Checked = (Get-Startup)
    $chkStartup.SetBounds(15, 108, 270, 22)

    $btnDefaults = New-Object System.Windows.Forms.Button
    $btnDefaults.Text = "Restore defaults"; $btnDefaults.SetBounds(15, 148, 110, 28)
    $btnDefaults.add_Click({
        $numMouse.Value = $DefaultMouseSpeed
        $numPad.Value = $DefaultTrackpadSpeed
        $chkAuto.Checked = $true
    })

    $btnSave = New-Object System.Windows.Forms.Button
    $btnSave.Text = "Save"; $btnSave.SetBounds(135, 148, 70, 28)
    $btnSave.DialogResult = 'OK'
    $btnCancel = New-Object System.Windows.Forms.Button
    $btnCancel.Text = "Cancel"; $btnCancel.SetBounds(210, 148, 70, 28)
    $btnCancel.DialogResult = 'Cancel'
    $form.AcceptButton = $btnSave
    $form.CancelButton = $btnCancel

    $form.Controls.AddRange(@($lblMouse, $numMouse, $lblPad, $numPad, $chkAuto, $chkStartup, $btnDefaults, $btnSave, $btnCancel))

    if ($form.ShowDialog() -eq 'OK') {
        $script:MouseSpeed    = [int]$numMouse.Value
        $script:TrackpadSpeed = [int]$numPad.Value
        $script:auto          = $chkAuto.Checked
        Save-Settings
        Build-Icons
        Set-Startup $chkStartup.Checked
        Set-Mode $script:currentMode -Force
        Set-Auto $chkAuto.Checked
    }
    $form.Dispose()
}

# Initial state from the current system speed
if ([MouseSpeed]::Get() -eq $script:TrackpadSpeed) { $script:currentMode = 'trackpad' } else { $script:currentMode = 'mouse' }
Build-Icons

$watcher = New-Object RawInputWatcher $MouseNameMatch
$watcher.HoldMs = $SwitchHoldMs
$watcher.add_DeviceChanged({
    param($kind)
    if ($script:auto) { Set-Mode $kind }
})

$tray.add_MouseClick({
    param($s, $e)
    if ($e.Button -eq [System.Windows.Forms.MouseButtons]::Left) {
        Set-Auto $false
        if ($script:currentMode -eq 'mouse') { Set-Mode 'trackpad' } else { Set-Mode 'mouse' }
    }
})
$itemAuto.add_Click({ Set-Auto $true })
$itemManual.add_Click({ Set-Auto $false })
$itemMouse.add_Click({ Set-Auto $false; Set-Mode 'mouse' })
$itemTrackpad.add_Click({ Set-Auto $false; Set-Mode 'trackpad' })
$itemSettings.add_Click({ Show-SettingsDialog })
$itemStartup.add_Click({ Set-Startup (-not (Get-Startup)) })
$itemInfo.add_Click({
    $kind = if ($watcher.LastKind -eq 'mouse') { 'MOUSE' } else { 'TRACKPAD' }
    [System.Windows.Forms.MessageBox]::Show(
        "Last device used (the one that clicked this menu):`n`n$($watcher.LastDeviceName)`n`nClassified as: $kind",
        "MouseSwitch") | Out-Null
})
$itemExit.add_Click({
    $tray.Visible = $false
    $tray.Dispose()
    foreach ($i in $script:icons.Values) { $i.Dispose() }
    $watcher.DestroyHandle()
    [System.Windows.Forms.Application]::Exit()
})

Update-Ui
$tray.Visible = $true
[System.Windows.Forms.Application]::Run()
$mutex.ReleaseMutex()
$mutex.Dispose()
exit
